data = LOAD '/network_project/raw/Monday-WorkingHours.pcap_ISCX.csv'
USING PigStorage(',')
AS (
    destination_port:int,
    flow_duration:long,
    total_fwd_packets:int,
    total_backward_packets:int,
    total_length_fwd_packets:double,
    total_length_bwd_packets:double,
    fwd_packet_length_max:double,
    fwd_packet_length_min:double,
    fwd_packet_length_mean:double,
    fwd_packet_length_std:double,
    bwd_packet_length_max:double,
    bwd_packet_length_min:double,
    bwd_packet_length_mean:double,
    bwd_packet_length_std:double,
    flow_bytes_per_sec:double,
    flow_packets_per_sec:double,
    flow_iat_mean:double,
    flow_iat_std:double,
    flow_iat_max:double,
    flow_iat_min:double,
    fwd_iat_total:double,
    fwd_iat_mean:double,
    fwd_iat_std:double,
    fwd_iat_max:double,
    fwd_iat_min:double,
    bwd_iat_total:double,
    bwd_iat_mean:double,
    bwd_iat_std:double,
    bwd_iat_max:double,
    bwd_iat_min:double,
    fwd_psh_flags:int,
    bwd_psh_flags:int,
    fwd_urg_flags:int,
    bwd_urg_flags:int,
    fwd_header_length:int,
    bwd_header_length:int,
    fwd_packets_per_sec:double,
    bwd_packets_per_sec:double,
    min_packet_length:double,
    max_packet_length:double,
    packet_length_mean:double,
    packet_length_std:double,
    packet_length_variance:double,
    fin_flag_count:int,
    syn_flag_count:int,
    rst_flag_count:int,
    psh_flag_count:int,
    ack_flag_count:int,
    urg_flag_count:int,
    cwe_flag_count:int,
    ece_flag_count:int,
    down_up_ratio:double,
    average_packet_size:double,
    avg_fwd_segment_size:double,
    avg_bwd_segment_size:double,
    fwd_header_length_2:int,
    fwd_avg_bytes_bulk:double,
    fwd_avg_packets_bulk:double,
    fwd_avg_bulk_rate:double,
    bwd_avg_bytes_bulk:double,
    bwd_avg_packets_bulk:double,
    bwd_avg_bulk_rate:double,
    subflow_fwd_packets:int,
    subflow_fwd_bytes:int,
    subflow_bwd_packets:int,
    subflow_bwd_bytes:int,
    init_win_bytes_forward:int,
    init_win_bytes_backward:int,
    act_data_pkt_fwd:int,
    min_seg_size_forward:int,
    active_mean:double,
    active_std:double,
    active_max:double,
    active_min:double,
    idle_mean:double,
    idle_std:double,
    idle_max:double,
    idle_min:double,
    label:chararray
);

clean_data = FILTER data BY destination_port IS NOT NULL;

result = FOREACH clean_data GENERATE
    destination_port,
    flow_duration,
    total_fwd_packets,
    total_backward_packets,
    flow_bytes_per_sec,
    flow_packets_per_sec,
    label;

STORE result INTO '/network_project/monday_processed'
USING PigStorage(',');
